binscripts: make indentation consistent

diff --git a/bin/clip b/bin/clip
--- a/bin/clip
+++ b/bin/clip
@@ -4,26 +4,26 @@
 # Linux).
 
 if [[ -t 0 ]]; then
-    if command -v xclip >/dev/null; then
-        xclip -display :0 -selection clipboard -out
-    elif command -v xsel >/dev/null; then
-        xsel --clipboard --output
-    elif command -v pbpaste >/dev/null; then
-        pbpaste
-    else
-        >&2 echo "No clipboard detected. Aborting."
-        exit 1
-    fi
+  if command -v xclip >/dev/null; then
+    xclip -display :0 -selection clipboard -out
+  elif command -v xsel >/dev/null; then
+    xsel --clipboard --output
+  elif command -v pbpaste >/dev/null; then
+    pbpaste
+  else
+    >&2 echo "No clipboard detected. Aborting."
+    exit 1
+  fi
 else
-    if command -v xclip >/dev/null; then
-        xclip -display :0 -selection clipboard -in
-    elif command -v xsel >/dev/null; then
-        xsel --clipboard --input
-    elif command -v pbcopy >/dev/null; then
-        pbcopy
-    else
-        >&2 echo "No clipboard detected. Aborting."
-        exit 1
-    fi
+  if command -v xclip >/dev/null; then
+    xclip -display :0 -selection clipboard -in
+  elif command -v xsel >/dev/null; then
+    xsel --clipboard --input
+  elif command -v pbcopy >/dev/null; then
+    pbcopy
+  else
+    >&2 echo "No clipboard detected. Aborting."
+    exit 1
+  fi
 fi
 
diff --git a/bin/rclip b/bin/rclip
--- a/bin/rclip
+++ b/bin/rclip
@@ -21,26 +21,26 @@ bin="${0##*/}"
 
 flags=
 while getopts p:i:l: opt; do
-    case $opt in
-        p) flags+=" -p $OPTARG" ;;
-        i) flags+=" -i $OPTARG" ;;
-        l) flags+=" -l $OPTARG" ;;
-        *) >&2 echo "Invalid option $OPTARG"
-           exit 1
-           ;;
-    esac
+  case $opt in
+    p) flags+=" -p $OPTARG" ;;
+    i) flags+=" -i $OPTARG" ;;
+    l) flags+=" -l $OPTARG" ;;
+    *) >&2 echo "Invalid option $OPTARG"
+       exit 1
+       ;;
+  esac
 done
 shift $((OPTIND-1))
 
 target="$1"
 if [[ $target ]]; then
-    if [[ -t 0 ]]; then
-        pb | $bin $target
-    else
-        ssh $flags -qt "$target" "pb" && echo "Sent to $target"
-    fi
+  if [[ -t 0 ]]; then
+    pb | $bin $target
+  else
+    ssh $flags -qt "$target" "pb" && echo "Sent to $target"
+  fi
 else
-    pb
+  pb
 fi
 
 # vim:set ft=sh:
