Dotfiles bankruptcy and rewrite! All hail, v2.0

diff --git a/bin/pushover b/bin/pushover
--- a/bin/pushover
+++ b/bin/pushover
@@ -1,39 +1,57 @@
 #!/usr/bin/env bash
 
-if [[ ! -f "$HOME/.private/config/pushover.conf" ]]; then
-    >&2 echo "No pushover config file found (~/.private/config/pushover.conf)"
-    exit 1
+#
+# Sends a pushover notification.
+#
+#   -t [TITLE]
+#   -m [MESSAGE]
+#   -p [PRIORITY_LEVEL]
+#   -u [URL]
+#   -U [URL_TITLE]
+#   -d [DEVICE]
+#
+
+set -e
+unset CDPATH
+
+secret_file=~/.secrets/pushover
+if [[ ! -f $secret_file ]]; then
+  >&2 echo "No pushover config file found"
+  exit 1
 fi
 
-message=
-title=
-priority=
+title=${2:+$1}
+message=${2:-$1}
+# priority=
 url=
+url_title=
 device=
 
 while getopts t:m:p:u:d: opt; do
-    case $opt in
-        t) title="$OPTARG" ;;
-        m) message="$OPTARG" ;;
-        p) priority="$OPTARG" ;;
-        u) url="$OPTARG" ;;
-        U) url_title="$OPTARG" ;;
-        d) device="$OPTARG" ;;
-        *) >&2 echo "Invalid option $OPTARG"
-           exit 1
-           ;;
-    esac
+  case $opt in
+    t) title="$OPTARG" ;;
+    m) message="$OPTARG" ;;
+    # p) priority="$OPTARG" ;;
+    u) url="$OPTARG" ;;
+    U) url_title="$OPTARG" ;;
+    d) device="$OPTARG" ;;
+    *) >&2 echo "Invalid option $OPTARG"
+       exit 1
+       ;;
+  esac
 done
 shift $((OPTIND-1))
 
-. "$HOME/.private/config/pushover.conf"
+#USER=...
+#TOKEN=...
+eval "$(gpg --decrypt $secret_file)"
 
 curl -s \
-    --form-string "token=$TOKEN" \
-    --form-string "user=$USER" \
-    --form-string "title=$title" \
-    --form-string "message=$message" \
-    --form-string "url=$url" \
-    --form-string "url_title=$url_title" \
-    --form-string "device=$device" \
-    https://api.pushover.net/1/messages.json
+  --form-string "token=$TOKEN" \
+  --form-string "user=$USER" \
+  --form-string "title=$title" \
+  --form-string "message=$message" \
+  --form-string "url=$url" \
+  --form-string "url_title=$url_title" \
+  --form-string "device=$device" \
+  https://api.pushover.net/1/messages.json
diff --git a/bin/replace b/bin/replace
--- a/bin/replace
+++ b/bin/replace
@@ -1,13 +1,27 @@
 #!/usr/bin/env bash
-#
+set -e
+unset CDPATH
+
 # Find and replace by a given list of files.
 #
 # replace foo bar **/*.rb
 
-find_this="$1"; shift
-replace_with="$1"; shift
+main() {
+  local search="$1"
+  local replace="$2"
+  shift 2
 
-items=( $(ag -l --nocolor "$find_this" "$@") )
-for item in ${items[@]}; do
-  sed -i "s/${find_this}/${replace_with}/g" "$item"
-done
+  for item in $(ag -l --nocolor "$search" "$@"); do
+    sed -i "s%${search//%/\\%}%${replace//%/\\%}%g" "$item"
+  done
+}
+
+# Show matches
+ag "$1"
+
+# Are you sure?
+read -rp "Confirm search+replace? (y/n)?" choice
+case $choice in
+  y|Y) main "$@" ;;
+  *) >&2 echo "Aborted"; exit ;;
+esac
