install/mac: uses cask to install apps via homebrew

diff --git a/install/mac b/install/mac
--- a/install/mac
+++ b/install/mac
@@ -1,8 +1,53 @@
 #!/bin/sh
 
-brew install wget curl git
-brew install apple-gcc42
-brew install tmux the_silver_search
-brew install macvim --devel --override-system-vim --with-lua
+app_exists() {
+    if [ -e /Applications/"$1".app ] || [ -e ~/Applications/"$1".app ]; then
+        return 0
+    else
+        return 1
+    fi
+}
 
-brew tap homebrew/dupes
+if ! is_mac; then
+    echo-r "==> Aborting. This isn't a mac!"
+    exit 1
+fi
+
+if [ ! -d /usr/local/Cellar ]; then
+    echo-g "==> Installing homebrew"
+    ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
+else
+    brew tap homebrew/dupes
+
+    brew install wget curl git
+    brew install tmux the_silver_search
+    brew install lua --with-completion
+    brew install macvim --devel --override-system-vim --with-lua
+    brew install vim --override-system-vi --with-lua --with-perl
+
+    brew tap phinze/homebrew-cask
+    brew install brew-cask
+
+    # Install the apps I find useful (that I don't get through the app store)
+    app_exists "LaunchBar" && brew cask install launchbar
+    app_exists "Dropbox" && brew cask install dropbox
+    app_exists "Google Chrome" && brew cask install google-chrome
+    app_exists "Adium" && brew cask install adium
+    app_exists "AppCleaner" && brew cask install app-cleaner
+    app_exists "CodeKit" && brew cask install codekit
+    app_exists "iTerm" && brew cask install iterm2
+    app_exists "Reggy" && brew cask install reggy
+    app_exists "NetNewsWire" && brew cask install net-news-wire
+    app_exists "Soulver" && brew cask install soulver
+    app_exists "Scrivener" && brew cask install scrivener
+    app_exists "Sequel Pro" && brew cask install sequel-pro
+    app_exists "Skype" && brew cask install skype
+    app_exists "Transmission" && brew cask install transmission
+    app_exists "Transmit" && brew cask install transmit
+    app_exists "VLC" && brew cask install vlc
+
+    # I get Sparrow though the app store
+    #app_exists "Sparrow" && brew cask install sparrow
+fi
+
+exit 0
